services:
  - type: web
    name: blogify
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - key: MONGO_URL
        value: "mongodb+srv://kingjunagadh737:meet366105@cluster0.jsabfth.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: PORT
        value: 8000
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        value: AKIA45N6PRSB2UX4KTSE
      - key: AWS_SECRET_ACCESS_KEY
        value: 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
      - key: S3_BUCKET_NAME
        value: geniusstudent24-blog-uploads
      - key: VAPID_PRIVATE_KEY
        value: Tvzq045xhxV7qF-Q17Dt8271d068ghwBp8gHAdLVDmw
      - key: VAPID_PUBLIC_KEY
        value: BGF5qtd5Q5SGYMKIBSPbmtAjxj5wlJX4W2TpKfG7FHL3-Ruep7Px-mhQOILg_C9IM-2VJWXB9EG2X7tVTxqA
